version: "3.8"

services:
  app:
    build: .
    container_name: bun_function_app
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: ["bun", "src/function.js"]
