# docker-compose.yml
version: '3.8' # Specifies the Compose file version

services:
  postgres:
    image: postgres:latest # Use the official PostgreSQL image (consider specifying a version like postgres:13 for production)
    container_name: my_postgres_db # Optional: Give the container a specific name
    # restart: always # Automatically restart the container if it stops
    ports:
      - "5432:5432" # Map port 5432 inside the container to port 5432 on the host machine
    volumes:
      - pgdata3:/var/lib/postgresql/data # Persist database data using a named volume

# To connect to the database from your local machine, use the following URL:
# postgres://localhost:5432

volumes:
  pgdata3: # Defines the named volume used above