version: '3.8'

services:
  app:
    build:
      context: .
      target: builder  # Use builder stage for development
    platform: linux/amd64  # Force Intel compatibility
    network_mode: "host"  # Keep host networking
    volumes:
      - ./:/app  # Live reload
      - /app/node_modules  # Isolate node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: bun run start  # Explicit start command