global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cockroachdb'
    static_configs:
      - targets:
        - 'roach1:8080'
        - 'roach2:8080'
        - 'roach3:8080'
        - 'roach4:8080'
        - 'roach5:8080'